[package]
name = "succotash"
version = "0.1.0"
authors = ["Andrei Stepanenko <ftvkyo@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4.14"
pretty_env_logger = "0.4.0"

clap = "2.33.3"

image = "0.23.14"
